### ISSUE TITLE
Update README with additional detail

### ISSUE THREAD

**Issue by cpursley** [cpursley/react-admin-low-code#7]
Follow this as an example:

https://github.com/dvasdekis/react-admin-hasura-firebase

**Comment by dvasdekis** [comment]
Hey @cpursley! If you don't have time to maintain this yourself, I'd be happy to take it on :)

I'm in the Hasura discord as 'dv' if you'd like a chat :)

**Comment by cpursley** [comment]
This is awesome. I haven't had time to expand react-admin-low-code, so glad to see someone take the general idea and run with it. I'll update the Readme to mention your repo when I have a chance.

What were doing in our production version of this is using Postgres and Hasura for auth following this approach in order to reduce external dependencies: https://github.com/sander-io/hasura-jwt-auth

**Comment by cpursley** [comment]
Okay, I added a mention of your fork in the README: https://github.com/cpursley/react-admin-low-code/blob/master/README.md#alternatives

Let's leave this issue open so others can find it.
